# This is the modified ansible 'hosts' file for elkstack project
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/IP can be a member of multiple groups
# You need only a [webservers] and [elkservers] group.

# List the IP Addresses of your webservers
# You should have at least 2 IP addresses
 [webservers]
## alpha.example.org
## beta.example.org
## 192.168.1.100
## 192.168.1.110

10.0.0.5 ansible_python_interpreter=/usr/bin/python3
10.0.0.6 ansible_python_interpreter=/usr/bin/python3
10.0.0.7 ansible_python_interpreter=/usr/bin/python3

 [elk]
10.2.0.4 ansible_python_interpreter=/usr/bin/python3
